services:
  db_postgres:
    image: postgres:16
    container_name: postgres
    env_file:
      - ./credentials/postgres.env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./seed/postgres.sql:/docker-entrypoint-initdb.d/init-postgres.sql:ro

  db_mongodb:
    image: mongo:7
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    env_file:
      - credentials/mongo.env
    volumes:
      - mongodb_data:/data/db
      - ./seed/mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

volumes:
  pgdata:
  mongodb_data: